name: Passwords
version: '2.6'
main: info.cho.passwords.Passwords
bootstrapper: info.cho.passwords.PasswordsBootstrapper
api-version: '1.21.9'
authors: [ HamburgBigJ ]
softdepend: [ "DiscordSRV", "PlaceholderAPI" ]

permissions:
  passwords.command.logout:
    default: op
    description: "Allows to use the /logout command"

  passwords.command.setplayerpassword:
    default: op
    description: "Allows to use the /setplayerpassword command"


