name: Passwords
version: '1.7'
main: cho.info.passwords.Passwords
api-version: '1.21'
authors: [ HamburgBigJ ]
softdepend: [ DiscordSRV ]

commands:
  preload:
    permission: passwords.reload
    permission-message: "You do not have permission to use this command"

  setpassword:
    permission: passwords.setpassword
    permission-message: "You do not have permission to use this command"