name: Passwords
version: '2.4'
main: info.cho.passwords.Passwords
api-version: '1.21.4'
authors: [ HamburgBigJ ]
softdepend: [ DiscordSRV ]

permissions:
  passwords.command.logout:
    default: op
    description: "Allows to use the /logout command"

  passwords.command.setplayerpassword:
    default: op
    description: "Allows to use the /setplayerpassword command"


