name: Passwords
version: '1.5'
main: info.cho.passwords.Passwords
api-version: '1.21.5'
authors: [ HamburgBigJ ]
softdepend: [ DiscordSRV ]

permissions:
  passwords.command.logout:
    default: op
    description: "Allows to use the /logout command"

  passwords.command.setplayerpassword:
    default: op
    description: "Allows to use the /setplayerpassword command"


