name: Passwords
version: '1.4'
main: cho.info.passwords.Passwords
api-version: '1.21'
authors: [ HamburgBigJ ]
softdepend: [ DiscordSRV ]

commands:
  preload:
    permission: passwords.reload

  setpassword:
    permission: passwords.setpassword